"use client"

import {
	Document,
	Page,
	View,
	Text,
	StyleSheet,
	pdf,
} from "@react-pdf/renderer"
import type { AnalyticsData } from "@/lib/analytics"

const styles = StyleSheet.create({
	page: { backgroundColor: "#0A0A0B", padding: 32, color: "#F4F5F6" },
	h1: { fontSize: 22, fontWeight: "bold" },
	sub: { fontSize: 10, color: "#A1A1AA", marginBottom: 18 },
	kpiRow: { flexDirection: "row", marginBottom: 20 },
	kpiCard: {
		flexGrow: 1,
		flexBasis: 0,
		marginHorizontal: 4,
		backgroundColor: "#131417",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#26272B",
		padding: 10,
	},
	kpiLabel: { fontSize: 8, color: "#A1A1AA", marginBottom: 4 },
	kpiValue: { fontSize: 13, fontWeight: "bold" },
	section: { fontSize: 12, fontWeight: "bold", marginTop: 10, marginBottom: 8 },
	bullet: { fontSize: 10, color: "#D4D4D8", marginBottom: 4 },
	barRow: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
	barLabel: { width: 120, fontSize: 9 },
	barTrack: {
		flexGrow: 1,
		height: 8,
		backgroundColor: "#1B1C20",
		borderRadius: 4,
		marginHorizontal: 8,
	},
	barFill: { height: 8, backgroundColor: "#10B981", borderRadius: 4 },
	barValue: { width: 70, fontSize: 9, textAlign: "right" },
	footer: { marginTop: 24, fontSize: 8, color: "#6B6C72" },
})

function inr(n: number): string {
	return "Rs " + Math.round(n).toLocaleString("en-IN")
}

function Kpi({ label, value }: { label: string; value: string }) {
	return (
		<View style={styles.kpiCard}>
			<Text style={styles.kpiLabel}>{label}</Text>
			<Text style={styles.kpiValue}>{value}</Text>
		</View>
	)
}

function ReportDocument({
	analytics,
	insights,
}: {
	analytics: AnalyticsData
	insights: string[]
}) {
	const maxCust = Math.max(
		1,
		...analytics.topCustomers.map((c) => c.amount)
	)
	return (
		<Document>
			<Page size="A4" style={styles.page}>
				<Text style={styles.h1}>Business Report</Text>
				<Text style={styles.sub}>Generated by Data Assistant</Text>

				<View style={styles.kpiRow}>
					<Kpi label="TOTAL SALES" value={inr(analytics.totalSales)} />
					<Kpi label="COLLECTED" value={inr(analytics.collected)} />
					<Kpi label="OUTSTANDING" value={inr(analytics.outstanding)} />
					<Kpi label="ORDERS" value={String(analytics.orderCount)} />
				</View>

				{insights.length > 0 && (
					<View>
						<Text style={styles.section}>Key Points</Text>
						{insights.map((line, i) => (
							<Text key={i} style={styles.bullet}>
								- {line}
							</Text>
						))}
					</View>
				)}

				<Text style={styles.section}>Top Customers</Text>
				{analytics.topCustomers.map((c, i) => {
					const pct = `${Math.round((c.amount / maxCust) * 100)}%`
					const fillStyle = [styles.barFill, { width: pct }]
					return (
						<View key={i} style={styles.barRow}>
							<Text style={styles.barLabel}>{c.customer}</Text>
							<View style={styles.barTrack}>
								<View style={fillStyle} />
							</View>
							<Text style={styles.barValue}>{inr(c.amount)}</Text>
						</View>
					)
				})}

				<Text style={styles.footer}>
					{analytics.customerCount} customers · {analytics.orderCount} orders
				</Text>
			</Page>
		</Document>
	)
}

export async function downloadReport(
	analytics: AnalyticsData,
	insights: string[]
): Promise<void> {
	const blob = await pdf(
		<ReportDocument analytics={analytics} insights={insights} />
	).toBlob()
	const url = URL.createObjectURL(blob)
	const a = document.createElement("a")
	a.href = url
	a.download = "business-report.pdf"
	a.click()
	URL.revokeObjectURL(url)
}
